name: pepe-the-clown
favicon: null
layout_spectrum: 0.9698006752878428
typography_spectrum: 0.34091979288496077
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9077392325270921
  lightness: 0.4675358822569251
  saturation: 0.8029541531577706
  rhythmicContrast: 0.28103406517766416
purpose: []
